// <auto-generated />
namespace CRUD_MEMBERS_BOARD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class cardsMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cardsMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202003220116213_cardsMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
